blank_issues_enabled: false
contact_links:
  - name: â“ Ask a question
    url: https://github.com/Sahomey-Technologies/sahomedb/discussions
    about: Ask general questions or share ideas on Discussions.
  - name: ğŸ’¬ Join Discord
    url: https://discord.gg/bDhQrdfsfgkqNP4
    about: Join the Discord server to help shape the future of SahomeDB.  